### ISSUE TITLE
2.4.0 Feedback

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#24]
I'm not sure how much of this is relevant as it looks like you're doing a complete rewrite for 2.5. Is there a better way for feedback than filing an issue? I'm still new to Github.

The first area, completed archive text label, should be relevant regardless. It's just my opinion, but I preferred the clean look of just the name without the "Archived as" subheading. This subheading also is removed for old operations if there are subsequent folders added, which causes the unique filename info to be "lost". I would prefer the item text be the final filename – which also indicates if a rename was needed for uniqueness. Adding the extension and icon (note: there appears to be a regression in 2.4.0 as I no longer get icons) further gives feedback that it's a completed/final state as opposed to the original folder. Basically at this point it would look just like the archive fie would in the Finder. That seems to be the most true way to display the final product of the tool.

Relatively small window size often causes the "archived as/path/filename" subheading to be truncated. If autosizing is not going to implemented, could you at least save the window state (size & position), so that the user can decide what size/position works best for them? If autosizing for width is not added, could you implement vertical autosize when number of items exceeds the default window height? At least as an option?

Adding a previously processed folder now works, but without icon and final filename, it's a confusing interface as the old and new items look about the same. I'm assuming this is just a work-in-progress issue. 

The "-1, -2, -3" unique filenames now work fine,

I'm still getting  delays on launch as droplet. Again may be moot for 2.5.

The app is progressing nicely. I'm excited to see where you do in the next version.

**Comment by pkrll** [comment]
Issues are pretty much the only way to give feedback, I guess.

But, in the future, try to file the bug reports/feature requests in separate issues, instead of in one post. It makes it easier for me to work through them.

I agree that the subheading should loose the "Archived as" part, wasn't really anything I thought through. The reason the subheading removed when a new folder is added is because of the total size calculations. This will of course not be a problem in 2.5.

I don't think autosizing is such a good idea (never mess with the user's windows), but I'll consider implementing saving window state.

I haven't look into the launch delay issue, it'll be after the rewrite (I'm doing it to actually go through all of the code and write it better, cleaner and, where possible, smaller).
